version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: rehab-oracle
    environment:
      - ORACLE_PWD=RehabCenter123!
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "sys/RehabCenter123!@//localhost:1521/XE", "AS", "SYSDBA", "@healthcheck.sql" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
